### ISSUE TITLE
breaks with datasets==2.8.0 

### ISSUE THREAD

**Issue by ArneBinder** [ChristophAlt/pytorch-ie#239]
This breaks any new setup.

Reproduce (on a fresh environment):
```python
from datasets import load_dataset
ds = load_dataset("pie/conll2003")
```

Result:
```
Found cached dataset conll2003 (/home/arbi01/.cache/huggingface/datasets/pie___conll2003/conll2003/1.0.0/2786c823a292d679df0f1e05f463e712b37321e504e3e91f592afca3cc54c340)
  0%|          | 0/3 [00:00<?, ?it/s]Loading cached processed dataset at /home/arbi01/.cache/huggingface/datasets/pie___conll2003/conll2003/1.0.0/2786c823a292d679df0f1e05f463e712b37321e504e3e91f592afca3cc54c340/cache-357d4073acee9620.arrow
Traceback (most recent call last):
  File "/home/arbi01/projects/pie-s2orc/debug.py", line 4, in <module>
    ds = load_dataset("pie/conll2003")
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/load.py", line 1769, in load_dataset
    ds = builder_instance.as_dataset(split=split, ignore_verifications=ignore_verifications, in_memory=keep_in_memory)
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/builder.py", line 1066, in as_dataset
    datasets = map_nested(
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 444, in map_nested
    mapped = [
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 445, in <listcomp>
    _single_map_nested((function, obj, types, None, True, None))
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 346, in _single_map_nested
    return function(data_struct)
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/builder.py", line 1109, in _build_single_dataset
    post_processed = self._post_process(ds, resources_paths)
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/pytorch_ie/data/builder.py", line 89, in _post_process
    document_dataset = Dataset.from_hf_dataset(
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/pytorch_ie/data/dataset.py", line 167, in from_hf_dataset
    document_dataset = cls(document_type=document_type, **cls.get_base_kwargs(dataset))
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/pytorch_ie/data/dataset.py", line 151, in __init__
    self.set_format("document", document_type=document_type)
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/fingerprint.py", line 480, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2326, in set_format
    _ = get_formatter(type, features=self.features, **format_kwargs)
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/datasets/formatting/__init__.py", line 125, in get_formatter
    return _FORMAT_TYPES[format_type](**format_kwargs)
  File "/home/arbi01/miniconda3/envs/pie-s2orc/lib/python3.9/site-packages/pytorch_ie/data/dataset_formatter.py", line 11, in __init__
    super().__init__(features=None, decoded=None)
TypeError: __init__() got an unexpected keyword argument 'decoded'
  0%|          | 0/3 [00:00<?, ?it/s]

Process finished with exit code 1
```

[This](https://github.com/huggingface/datasets/blame/2.8.0/src/datasets/formatting/formatting.py#L399 ) seems to be the culprit. The `decoded` parameter was removed, but we pass `None` in the `DocumentFormatter`, see [here](https://github.com/ChristophAlt/pytorch-ie/blob/main/src/pytorch_ie/data/dataset_formatter.py#L11).

**Comment by ArneBinder** [comment]
@ChristophAlt For now, can we have a version of pytorch-ie that defines datasets 2.7.1 as the max version? I tested that and it works. I'm not familiar with the dependency setup, maybe can you step in?
